🔧 Update CI

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -20,5 +20,5 @@ jobs:
       - name: Run tests
         run: |
           ./pact ./gielinorian/tests/init.repl > output.txt
-          if [ "$(grep "Load successful" out.txt|wc -l )" -eq 19 ]; then echo "Tests Succeeded"; exit 0; else echo "Tests Failed";exit 1; fi
+          if [ "$(grep "Load successful" output.txt|wc -l )" -eq 19 ]; then echo "Tests Succeeded"; exit 0; else echo "Tests Failed";exit 1; fi
     
